FROM node:18

WORKDIR /app

# Copiar código REST y protos
COPY ./servicios/rutasREST ./rutasREST
COPY ./servicios/protos ./protos
COPY package*.json ./

RUN npm install

EXPOSE 3000

CMD ["node", "src/server.js"]  # Cambia a tu entrypoint real de REST
